version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./datasets:/app/datasets
      - ./server-memory:/app/server-memory
    environment:
      - NODE_ENV=development
